version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  version: 2
  default:
    jobs:
      - validate
      - publish-branch:
          requires:
            - validate
          filters:
            branches:
              ignore: master
      - publish:
          requires:
            - validate
          filters:
            branches:
              only: master

jobs:
  validate:
    executor: circleci-cli/default
    steps:
      - checkout
      - orb-tools/validate:
          orb-path: orb.yml
  publish-branch:
    executor: circleci-cli/default
    steps:
      - checkout
      - orb-tools/publish:
          orb-path: orb.yml
          orb-ref: convox/orb@dev:${CIRCLE_BRANCH}
          token-variable: "$CIRCLECI_DEV_API_TOKEN"
  publish:
    executor: circleci-cli/default
    steps:
      - checkout
      - orb-tools/increment:
          orb-path: orb.yml
          orb-ref: convox/orb
          segment: patch
          token-variable: "$CIRCLECI_DEV_API_TOKEN"
