version: 2.1

orbs:
  circleci-cli: circleci/circleci-cli@0.1.2
  orb-tools: circleci/orb-tools@2.0.0

workflows:
  version: 2
  default:
    jobs:
      - orb-tools/publish:
          name: publish
          orb-path: orb.yml
          orb-ref: convox/orb@dev:${CIRCLE_BRANCH}
          validate: true
      - orb-tools/publish:
          name: release
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
          orb-path: orb.yml
          orb-ref: convox/orb@${CIRCLE_TAG}
          validate: true
